name: WebdriverIO Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for BrowserStack
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}" >> .env
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}" >> .env
          echo "BROWSERSTACK_ANDROID_APP_ID=${{ secrets.BROWSERSTACK_APP_ID }}" >> .env

      - name: Install Appium and dependencies
        run: |
          npm install -g appium
          npm install -g @appium/doctor
          appium-doctor --android # Проверка конфигурации для Android

      - name: Run WebdriverIO tests on BrowserStack
        run: npm run test:android:bs
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-test-results
          path: allure-report/

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
