name: WebdriverIO Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_BUCKET_NAME=${{ secrets.FIREBASE_BUCKET_NAME }}" >> .env
          echo "FIREBASE_IOS_APP_PATH=${{ secrets.FIREBASE_IOS_APP_PATH }}" >> .env
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> .env

      - name: Install Appium and dependencies
        run: |
          npm install -g appium
          appium driver install xcuitest
          npm install -g @appium/doctor
          appium-doctor --ios # To check if everything is set up correctly

      - name: Run WebdriverIO tests for iOS on Firebase
        run: npm run test:ios:firebase
        continue-on-error: true 

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: webdriverio-test-results
          path: ./reporters/allure-results/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-test-results
          path: allure-report/

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
